/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 1
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'manage',
    path: '/manage',
    component: 'layout.base',
    meta: {
      title: 'manage',
      i18nKey: 'route.manage',
      icon: 'carbon:cloud-service-management',
      order: 9,
      roles: ['R_ADMIN']
    },
    children: [
      {
        name: 'manage_activity',
        path: '/manage/activity',
        component: 'view.manage_activity',
        meta: {
          title: 'manage_activity',
          i18nKey: 'route.manage_activity'
        }
      },
      {
        name: 'manage_activitycategory',
        path: '/manage/activitycategory',
        component: 'view.manage_activitycategory',
        meta: {
          title: 'manage_activitycategory',
          i18nKey: 'route.manage_activitycategory'
        }
      },
      {
        name: 'manage_api-log',
        path: '/manage/api-log',
        component: 'view.manage_api-log',
        meta: {
          title: 'manage_api-log',
          i18nKey: 'route.manage_api-log'
        }
      },
      {
        name: 'manage_banner',
        path: '/manage/banner',
        component: 'view.manage_banner',
        meta: {
          title: 'manage_banner',
          i18nKey: 'route.manage_banner'
        }
      },
      {
        name: 'manage_cache-list',
        path: '/manage/cache-list',
        component: 'view.manage_cache-list',
        meta: {
          title: 'manage_cache-list',
          i18nKey: 'route.manage_cache-list',
          icon: 'mdi:database-search',
          order: 11,
          roles: ['R_ADMIN']
        }
      },
      {
        name: 'manage_cache-monitor',
        path: '/manage/cache-monitor',
        component: 'view.manage_cache-monitor',
        meta: {
          title: 'manage_cache-monitor',
          i18nKey: 'route.manage_cache-monitor',
          icon: 'mdi:monitor-dashboard',
          order: 10,
          roles: ['R_ADMIN']
        }
      },
      {
        name: 'manage_config',
        path: '/manage/config',
        component: 'view.manage_config',
        meta: {
          title: 'manage_config',
          i18nKey: 'route.manage_config'
        }
      },
      {
        name: 'manage_dept',
        path: '/manage/dept',
        component: 'view.manage_dept',
        meta: {
          title: 'manage_dept',
          i18nKey: 'route.manage_dept'
        }
      },
      {
        name: 'manage_dict',
        path: '/manage/dict',
        component: 'view.manage_dict',
        meta: {
          title: 'manage_dict',
          i18nKey: 'route.manage_dict'
        }
      },
      {
        name: 'manage_dynamics',
        path: '/manage/dynamics',
        component: 'view.manage_dynamics',
        meta: {
          title: 'manage_dynamics',
          i18nKey: 'route.manage_dynamics'
        }
      },
      {
        name: 'manage_file-manage',
        path: '/manage/file-manage',
        component: 'view.manage_file-manage',
        meta: {
          title: 'manage_file-manage',
          i18nKey: 'route.manage_file-manage'
        }
      },
      {
        name: 'manage_login-log',
        path: '/manage/login-log',
        component: 'view.manage_login-log',
        meta: {
          title: 'manage_login-log',
          i18nKey: 'route.manage_login-log'
        }
      },
      {
        name: 'manage_menu',
        path: '/manage/menu',
        component: 'view.manage_menu',
        meta: {
          title: 'manage_menu',
          i18nKey: 'route.manage_menu',
          icon: 'material-symbols:route',
          order: 3,
          roles: ['R_ADMIN'],
          keepAlive: true
        }
      },
      {
        name: 'manage_operation-log',
        path: '/manage/operation-log',
        component: 'view.manage_operation-log',
        meta: {
          title: 'manage_operation-log',
          i18nKey: 'route.manage_operation-log'
        }
      },
      {
        name: 'manage_oss-config',
        path: '/manage/oss-config',
        component: 'view.manage_oss-config',
        meta: {
          title: 'manage_oss-config',
          i18nKey: 'route.manage_oss-config'
        }
      },
      {
        name: 'manage_post',
        path: '/manage/post',
        component: 'view.manage_post',
        meta: {
          title: 'manage_post',
          i18nKey: 'route.manage_post'
        }
      },
      {
        name: 'manage_role',
        path: '/manage/role',
        component: 'view.manage_role',
        meta: {
          title: 'manage_role',
          i18nKey: 'route.manage_role',
          icon: 'carbon:user-role',
          order: 2,
          roles: ['R_SUPER']
        }
      },
      {
        name: 'manage_system-monitor',
        path: '/manage/system-monitor',
        component: 'view.manage_system-monitor',
        meta: {
          title: 'manage_system-monitor',
          i18nKey: 'route.manage_system-monitor'
        }
      },
      {
        name: 'manage_topic',
        path: '/manage/topic',
        component: 'view.manage_topic',
        meta: {
          title: 'manage_topic',
          i18nKey: 'route.manage_topic'
        }
      },
      {
        name: 'manage_user',
        path: '/manage/user',
        component: 'view.manage_user',
        meta: {
          title: 'manage_user',
          i18nKey: 'route.manage_user',
          icon: 'ic:round-manage-accounts',
          order: 1,
          roles: ['R_ADMIN']
        }
      },
      {
        name: 'manage_user-detail',
        path: '/manage/user-detail/:id',
        component: 'view.manage_user-detail',
        props: true,
        meta: {
          title: 'manage_user-detail',
          i18nKey: 'route.manage_user-detail',
          hideInMenu: true,
          roles: ['R_ADMIN'],
          activeMenu: 'manage_user'
        }
      }
    ]
  },
  {
    name: 'user-center',
    path: '/user-center',
    component: 'layout.base$view.user-center',
    meta: {
      title: 'user-center',
      i18nKey: 'route.user-center',
      hideInMenu: true
    }
  }
];
